#!/bin/bash
cd ~/.darbs
sudo chmod 644 ~/.darbs/dotfiles/common/.ssh/*
git secret hide
sudo chmod 400 ~/.darbs/dotfiles/common/.ssh/*
git add -A
git commit -m "update"
git pull origin HEAD
git add -A
git commit -m "merge"
git push origin HEAD
# ls -lisa ~/.darbs/dotfiles/common/.ssh
cd -
