#!/bin/bash
datetime=$(date '+%Y%m%d_%H%M%S')
if [[ ! -z ${1} ]]; then
	cd "$1" || return
	git add -A
	if [[ -z "${2}" ]]; then
		git pu ":running: anon (${datetime})"
	else
		git pu ":shipit: ${2} (${datetime})"
	fi
fi
