#!/bin/bash
tmux split-window -v -t $TMUX_PANE
tmux send-keys "bash" Enter
tmux send-keys "source /home/mod/.darbs/scripts/common/forgit" Enter
tmux send-keys "clear" Enter
tmux send-keys "forgit_choose" Enter
