#!/bin/bash
# file=$(find "${1}"/* -maxdepth 9 -type f ! -path '*.git*' | fzf)
# if [[ -n "${file}" ]]; then

  # if [[ "${file}" == *".pdf"* ]]; then
    # i3-msg "exec zathura '${file}'"
  # else
    # vim "${file}"
  # fi

# fi
file=$(find "${1}"/* -maxdepth 9 -type f ! -path '*.git*' | fzf)
if [[ -n "${file}" ]]; then
  if [[ "${file}" == *".pdf"* ]]; then
    i3-msg "exec zathura '${file}'"
  else
    # path_file="$(dirname "${file}")" 
    # tmux send-keys "cd ${path_file}" ENTER
    # sleep 2
    tmux rename-window "$(basename "${file}")"
    vim "${file}" -c ":cd %:p:h"
  fi
fi
