#!/bin/bash
set -eu -o pipefail

# ==============================================================================
# Links
# https://superuser.com/questions/177445/how-to-list-printer-names-acceptable-for-use-with-lpr

# ==============================================================================
# TODO
# - choose maxdepth (. no depth; 1..n -maxdepth)
# - add file chooser (fzf -m) <TAB> to mark multiple items (-f)
# - open cups browser (-o)

# ==============================================================================

# Paths
: "${BASEDIR:="$(git rev-parse --show-toplevel)"}"

# Options
: "${SCRIPT_ACTION:="?"}"            # Action
: "${TEST:=""}"                      # -t
: "${DRY_RUN:="false"}"              # -d

# Variables
: "${PRINTER:=""}"                   # can be set by set_printer

# ==============================================================================
# Imports

# shellcheck disable=SC1091
# source "${BASEDIR}/scripts/libs/verbose.sh"

# ==============================================================================
# Usage

# ------------------------------------------------------------------------------
usage() {
  local -r message="${1:-""}"

  [ -n "${message}" ] &&
    echo -e "\n\033[31m■■\033[0m \033[1m${message}\033[0m\n"
  cat <<-EOTXT
Usage:
   [options]

Options:
  -t STRING       (TODO) Test
  -d BOOLEAN      Dry run?
  -h              Help

Actions:
  -D              Set default printer
  -T              Test
  -B              Print for Booking
EOTXT
  [ -z "${message}" ] && exit 0 || exit 1
}

# ------------------------------------------------------------------------------
arguments() {
  while getopts t:dBDT opt; do
    case "${opt}" in
    # options
    t) TEST="${OPTARG}" ;;
    d) DRY_RUN="true" ;;
    B | D | T)
      SCRIPT_ACTION="${opt}"
      ;;
    *) usage "You passed a non existant option! What is it you want to do?" ;;
    esac
  done
  shift $((OPTIND - 1))
}

# ==============================================================================
# Helpers

# ------------------------------------------------------------------------------
# TODO document
set_printer() {
  echo "Running set_printer()"
  PRINTER=$(lpstat -a | while read -r printer_line; do
    # shellcheck disable=SC2001
    echo "${printer_line}" |  sed -e 's/\s.*$//'
  done | fzf)
}

# ==============================================================================
# Actions

# ------------------------------------------------------------------------------
# TODO document
# TODO mv to printed, when done
print_for_booking() {
  echo "Running print_for_booking()"
  if [[ ! "${DRY_RUN}" = "true" ]]; then
    set_printer
    mkdir tmp
  fi
  find . -maxdepth 1 -name "*.pdf" ! -path "./_*" -print0 | sort -z | while IFS= read -r -d $'\0' src_file; do
    filename=$(basename "${src_file}")
    number=$(echo "${filename}" | cut -c1-9)
    echo "Print ${filename}"
    if [[ "${DRY_RUN}" = "true" ]]; then
      echo "number: ${number}"
      echo "filename: ${filename}"
    else
      pdfjam --outfile "tmp/${filename}" --pagecommand "{========== ${number} ===========}" "${filename}"
      if [[ -z "${PRINTER}" ]]; then
        echo "No Printer choosen!"
      else
        lp -d "${PRINTER}" "tmp/${filename}"
      fi
    fi
  done
  if [[ ! "${DRY_RUN}" = "true" ]]; then
    rm -rf tmp
    nohup "${BROWSER}" http://localhost:631/jobs/ >/dev/null 2>&1 &
  fi
}

# ------------------------------------------------------------------------------
set_default_printer() {
  echo "Running set_default_printer()"
  DEFAULT_PRINTER=$(lpstat -a | while read -r printer_line; do
    # shellcheck disable=SC2001
    echo "${printer_line}" |  sed -e 's/\s.*$//'
  done | fzf)
  lpoptions -d "${DEFAULT_PRINTER}"
}

# ==============================================================================
# Execute
main() {
  arguments "${@}"

  case "${SCRIPT_ACTION}" in
  "B") # print for booking
    print_for_booking
    ;;
  "D") # print for booking
    set_default_printer
    ;;
  "T") # TODO
    set_printer
    ;;
  "?") # Help when no Option
    usage "You passed no option! What is it you want to do?"
    ;;
  esac
}

# ------------------------------------------------------------------------------
# execute if called directly
[[ "${0}" == "${BASH_SOURCE[0]}" ]] && main "${@}"
