#!/bin/bash
# corresponds to vim_last_edited_save
# test -> find ~/.darbs/scripts/common -type f -name "vim_last_edited*" | entr vim_last_edited_open 4 /home/mod
# TODO create new log for every day
# TODO remove UPDATE.md and /tmp/tmp from output (use array)
tmux_window_num="${1}"
num="${2}"
if [[ -n "${3}" ]]; then
  path_base="${3}"
else
  path_base=$(pwd)
fi
file_last_edited_log="${path_base}/.ide/last_edited.log"

if [[ -f "${file_last_edited_log}" ]] && [[ -s "${file_last_edited_log}" ]] ; then
  # inspired by https://unix.stackexchange.com/questions/194780/remove-duplicate-lines-while-keeping-the-order-of-the-lines
  clear
  cd "${path_base}"
  # cmd_vim=$(cat -n "${file_last_edited_log}" | sort -k4 -k1n | uniq -f1 -f2 -f3 | sort -nk1,1 | awk '{print $5;}' | head -n "${num}" | tr '\n' ' ' | xargs -I _files echo "vim -p _files")
  cmd_vim="vim "
  while read file; do
    file_log="${path_base}/${file}"
    if [[ -f "${file_log}" ]]; then
      cmd_vim="${cmd_vim} ${file}"
    fi
  done < <(cat -n "${file_last_edited_log}" | sort -k4 -k1n | uniq -f1 -f2 -f3 | sort -nk1,1 | awk '{print $5;}' | head -n "${num}"  | xargs -I _file echo "_file")
else
  cmd_vim="vim -c ':Ranger'"
fi
# echo " ${cmd_vim}"
# eval "${cmd_vim}"
# tmux send-keys -t "cops:${tmux_window_num}.0" "${cmd_vim}" Enter
# echo "${tmux_window_num}"
sleep 5
tmux list-panes -s | grep $TMUX_PANE | awk '{print $1;}' | tr -d ':' | xargs -I _pane tmux send-keys -t $(tmux display-message -p '#S')":_pane" "bash -c \"${cmd_vim}\"" Enter
# tmux list-panes -s | grep $TMUX_PANE | awk '{print $1;}' | tr -d ':' | xargs -I _pane tmux send-keys -t $(tmux display-message -p '#S')":_pane" "${cmd_vim}" Enter
