#!/bin/bash

# helper
wik_path="${HOME}/art/wik"
cat_path="${wik_path}/ref"
src_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/$(basename "$0")"

# files
f1="${cat_path}/senior_developer/project.md"
f2="${cat_path}/vim/project.md"
f3="${cat_path}/wiki/project.md"
f4="${cat_path}/manjaro/project.md"
f5="${cat_path}/admin/project.md"

# run
cd "${wik_path}" || exit
vim -p "${f5}" "${f1}" "${f2}" "${f3}" "${f4}" "${src_path}"
