# FISH abbrs.fish

# abbr g 'git'
abbr .. 'cd .. && ls'
abbr ... 'cd ../.. && ls'
abbr .... 'cd ../../.. && ls'
abbr ..... 'cd ../../../.. && ls'
abbr ...... 'cd ../../../../.. && ls'
abbr ....... 'cd ../../../../../.. && ls'
abbr ........ 'cd ../../../../../../.. && ls'
abbr awkprint "awk '{print \$1;}'"
abbr vt 'vim -c ":terminal ++curwin"'
abbr b 'bash'
abbr chm 'sudo chmod +x'
abbr cho 'sudo chown'
abbr tu 'tmuxpUtils -S'
abbr ci 'cicd'
abbr cf 'cloudflareU'
abbr dg 'ddgr'
abbr dia 'cd ~/art/wik && vim -c ":VimwikiMakeDiaryNote"'
abbr diat 'cd ~/art/wik && vim -c ":VimwikiMakeTomorrowDiaryNote"'
abbr diay 'cd ~/art/wik && vim -c ":VimwikiMakeYesterdayDiaryNote"'
abbr do 'devopsU'
abbr vr 'vim README.md'
abbr es 'echo $status'
abbr f 'fish'
abbr g 'googler'
abbr ga 'git add'
abbr gb 'git branch'
abbr gbl 'git blame'
abbr gc 'git commit -m'
abbr gcgh 'git clone git@github.com:divramod/'
abbr gcgl 'git clone git@gitlab.com:divramod/'
abbr gco 'git checkout'
abbr gcp 'git cherry-pick'
abbr gcs 'git clone --recurse-submodules -j8'
abbr gd 'git diff'
abbr gf 'git fetch'
abbr gl 'git log'
abbr gm 'git merge'
abbr gop 'git open'
abbr gp 'git push'
abbr gpl 'git pull'
abbr gpoh 'git push origin HEAD'
abbr gpom 'git push origin master'
abbr gr 'git remote'
abbr gra 'git remote a'
abbr grs 'git remote set-url'
abbr grv 'git remote -v'
abbr gs 'git status'
abbr gst 'git stash'
abbr gsu 'git submodule update --recursive --remote'
abbr hcl 'hcloud context list'
abbr hfl 'hcloud floating-ip list'
abbr hh 'hcloud help'
abbr hsl 'hcloud server list'
abbr ir 'i3-msg reload; i3-msg restart'
abbr is '/home/mod/cod/wo/thingylabs/kubernetes-provisioning/utils/plugins/istio'
abbr k 'kubectl'
abbr l 'ls -lisa'
abbr lh 'ls -a --format=horizontal'
abbr ld 'ls -lgot --time-style=long-iso'
abbr le 'ls -lgo --sort=extension'
abbr lr 'ls -sSh'
abbr lv 'ls -lgo --sort=version'
abbr mb '/home/mod/cod/wo/thingylabs/kubernetes-provisioning/utils/plugins/metallb'
abbr mf 'tmuxp freeze'
abbr ml 'tmuxp load -y'
abbr mv 'mv'
abbr p 'sudo pacman -S'
abbr r 'ranger'
abbr spa 'vim ~/art/wik/inb/sparkfile.md'
abbr ta 'testing -A'
abbr tk 'tmux kill-session'
abbr tks 'tmux kill-server'
abbr tml 'tmux display-message -p "#{window_layout}"'
abbr ts 'testing -S'
abbr v 'vim'
abbr vn 'vim -c "NERDTree | wincmd l"'
abbr y 'yay -S'
abbr os 'operator-sdk'

# THINGYLABS
# ==============================================================================
# MISC
# ------------------------------------------------------------------------------
abbr ep 'echo $PLAYBOOK_NAME'
abbr ek 'echo $KUBECONFIG'
abbr epa 'echo $PATH'
abbr da 'direnv allow && test -f ../.env && source ../.env && cat ../.env'
abbr ops1 'cd ~/cod/wo/thingylabs/devops1 && direnv allow && test -f ../.env && source ../.env && cat ../.env'
abbr ops2 'cd ~/cod/wo/thingylabs/devops2 && direnv allow && test -f ../.env && source ../.env && cat ../.env'
abbr ops3 'cd ~/cod/wo/thingylabs/devops3 && direnv allow && test -f ../.env && source ../.env && cat ../.env'
abbr ops4 'cd ~/cod/wo/thingylabs/devops4 && direnv allow && test -f ../.env && source ../.env && cat ../.env'
abbr nia1 'cd ~/cod/wo/thingylabs/calponia1 && direnv allow && test -f ../.env && source ../.env && cat ../.env'
abbr nia2 'cd ~/cod/wo/thingylabs/calponia2 && direnv allow && test -f ../.env && source ../.env && cat ../.env'
abbr nia3 'cd ~/cod/wo/thingylabs/calponia3 && direnv allow && test -f ../.env && source ../.env && cat ../.env'
abbr nia4 'cd ~/cod/wo/thingylabs/calponia4 && direnv allow && test -f ../.env && source ../.env && cat ../.env'
abbr bot1 'cd ~/cod/wo/thingylabs/calpobot1 && direnv allow && test -f ../.env && source ../.env && cat ../.env'
abbr bot2 'cd ~/cod/wo/thingylabs/calpobot1 && direnv allow && test -f ../.env && source ../.env && cat ../.env'
abbr bot3 'cd ~/cod/wo/thingylabs/calpobot1 && direnv allow && test -f ../.env && source ../.env && cat ../.env'
abbr tl 'cd ~/cod/wo/thingylabs && ls -lisa'
abbr tld 'cd ~ && cd ~/cod/wo/thingylabs/devops && ls'
abbr tlc 'cd ~ && cd ~/cod/wo/thingylabs/calponia && ls -lisa'
abbr tlk 'cd ~ && cd ~/cod/wo/thingylabs/kubespray && ls -lisa'
abbr tlb 'cd ~ && cd ~/cod/wo/thingylabs/bats && ls -lisa'

# ISTIO
# ------------------------------------------------------------------------------
# from: https://blog.jayway.com/2018/10/22/understanding-istio-ingress-gateway-in-kubernetes/
# Port forward to the first ingress istio gateways
abbr istio_portforward 'kubectl -n istio-system port-forward (kubectl -n istio-system get pods -listio=ingressgateway -o=jsonpath="{.items[0].metadata.name}") 15000'
# Get the http routes from the port-forwarded ingressgateway pod (requires jq)
abbr istio_routes 'curl --silent http://localhost:15000/config_dump | jq '\''.configs.routes.dynamic_route_configs[].route_config.virtual_hosts[]| {name: .name, domains: .domains, route: .routes[].match.prefix}'\'''
# Get the logs of the first istio-ingressgateway pod
# Shows what happens with incoming requests and possible errors
abbr istio_logs 'kubectl -n istio-system logs (kubectl -n istio-system get pods -listio=ingressgateway -o=jsonpath="{.items[0].metadata.name}") --tail=300'
# Get the logs of the first istio-pilot pod
# Shows issues with configurations or connecting to the Envoy proxies
abbr istio_envoy 'kubectl -n istio-system logs $(kubectl -n istio-system get pods -listio=pilot -o=jsonpath="{.items[0].metadata.name}") discovery --tail=300'
