# FISH abbrs.fish

abbr .. 'cd .. && ls'
abbr ... 'cd ../.. && ls'
abbr .... 'cd ../../.. && ls'
abbr ..... 'cd ../../../.. && ls'
abbr b 'bash'
abbr chm 'sudo chmod +x'
abbr cho 'sudo chown'
abbr f 'fish'
abbr g 'git'
abbr ga 'git add'
abbr gb 'git branch'
abbr gbl 'git blame'
abbr gc 'git commit -m'
abbr gcgh 'git clone git@github.com:divramod/'
abbr gcgl 'git clone git@gitlab.com:divramod/'
abbr gcs 'git clone --recurse-submodules -j8'
abbr gco 'git checkout'
abbr gcp 'git cherry-pick'
abbr gd 'git diff'
abbr gf 'git fetch'
abbr gl 'git log'
abbr gm 'git merge'
abbr gp 'git push'
abbr gpl 'git pull'
abbr gpoh 'git push origin HEAD'
abbr gpom 'git push origin master'
abbr gr 'git remote'
abbr gra 'git remote a'
abbr grs 'git remote set-url'
abbr grv 'git remote -v'
abbr gs 'git status'
abbr gst 'git stash'
abbr go 'git open'
abbr ir 'i3-msg reload; i3-msg restart'
abbr mv 'mv'
abbr p 'sudo pacman -S'
abbr r 'ranger'
abbr v 'vim'
abbr vn 'vim -c "NERDTree | wincmd l"'
abbr y 'yay -S'
abbr ml 'tmuxp load -y'
abbr mf 'tmuxp freeze'
abbr tk 'tmux kill-session'
abbr tks 'tmux kill-server'
abbr spa 'vim ~/art/wik/inb/sparkfile.md'
abbr dia 'cd ~/art/wik && vim -c ":VimwikiMakeDiaryNote"'
abbr diat 'cd ~/art/wik && vim -c ":VimwikiMakeTomorrowDiaryNote"'
abbr diay 'cd ~/art/wik && vim -c ":VimwikiMakeYesterdayDiaryNote"'
abbr k 'kubectl'
