# vim: filetype=sh
abbr a "cd ~/art; and ls -a"
abbr aa "cd ~/art/sca; and ls -a"
abbr ab "cd ~/art/bac; and ls -a"
abbr ac "cd ~/art/cam; and ls -a"
abbr ad "cd ~/art/doc; and ls -a"
abbr ae "cd ~/art/ema; and ls -a"
abbr aj "cd ~/art/jou; and ls -a"
abbr an "cd ~/art/not; and ls -a"
abbr ap "cd ~/art/pro; and ls -a"
abbr ar "cd ~/art/ref; and ls -a"
abbr as "cd ~/art/scr; and ls -a"
abbr at "cd ~/art/tpl; and ls -a"
abbr aw "cd ~/art/wik; and ls -a"
abbr c "cd ~/.config; and ls -a"
abbr h "cd ~; and ls -a"
abbr co "cd ~/cod; and ls -a"
abbr cob "cd ~/cod/bb; and ls -a"
abbr coh "cd ~/cod/gh; and ls -a"
abbr col "cd ~/cod/gl; and ls -a"
abbr cot "cd ~/cod/te; and ls -a"
abbr cow "cd ~/cod/wo; and ls -a"
abbr d "cd ~/.darbs; and ls -a"
abbr dsa "cd ~/.darbs/scripts/arch_manjaro_i3; and ls -a"
abbr dsc "cd ~/.darbs/scripts/common; and ls -a"
abbr dst "cd ~/.darbs/scripts/termux; and ls -a"
abbr dc "cd ~/doc; and ls -a"
abbr de "cd ~/des; and ls -a"
abbr dw "cd ~/dow; and ls -a"
abbr ma "cd ~/med/aud; and ls -a"
abbr me "cd ~/med/ebo; and ls -a"
abbr mi "cd ~/med/img; and ls -a"
abbr mm "cd ~/med/mus; and ls -a"
abbr mp "cd ~/med/pic; and ls -a"
abbr ms "cd ~/med/sof; and ls -a"
abbr md "cd ~/med/vid; and ls -a"
abbr t "cd ~/.tmuxp; and ls -a"
abbr vc "cd ~/.config/nvim; and ls -a"
abbr va "cd ~/.config/nvim/pack; and ls -a"
abbr vb "cd ~/vbo; and ls -a"
abbr vp "cd ~/.config/nvim/plugged; and ls -a"
abbr vs "cd ~/.config/nvim/plugged/vim-snippets; and ls -a"
abbr rb "cd /boot; and ls -a"
abbr re "cd /etc; and ls -a"
abbr rh "cd /home; and ls -a"
abbr rl "cd /lost+found; and ls -a"
abbr rn "cd /mnt; and ls -a"
abbr ro "cd /opt; and ls -a"
abbr rp "cd /proc; and ls -a"
abbr rr "cd /root; and ls -a"
abbr rru "cd /run; and ls -a"
abbr rs "cd /srv; and ls -a"
abbr rt "cd /tmp; and ls -a"
abbr ru "cd /usr; and ls -a"
abbr rv "cd /var; and ls -a"
abbr ptl "cd ~/cod/wo/thingylabs/kubernetes-provisioning; and ls -a"
abbr ptlc "cd ~/cod/wo/thingylabs/calponia; and ls -a"
abbr .a "$EDITOR ~/.aliasrc"
abbr .b "$EDITOR ~/.bashrc"
abbr .bd "$EDITOR ~/.bmdirs"
abbr .bf "$EDITOR ~/.bmfiles"
abbr .d "$EDITOR ~/.darbs/darbs"
abbr .db "$EDITOR ~/.darbs/secrets/backup.csv"
abbr .df "$EDITOR ~/.darbs/secrets/folders.csv"
abbr .dm "$EDITOR ~/.darbs/secrets/mounts.csv"
abbr .dpa "$EDITOR ~/.darbs/rice/arch_manjaro_i3/progs.csv"
abbr .dpt "$EDITOR ~/.darbs/rice/termux/progs.csv"
abbr .dr "$EDITOR ~/.darbs/README.md"
abbr .ds "$EDITOR ~/.darbs/secrets/sync.csv"
abbr .dsa "$EDITOR ~/.darbs/scripts/arch_manjaro_i3"
abbr .dsc "$EDITOR ~/.darbs/scripts/common"
abbr .dst "$EDITOR ~/.darbs/scripts/termux"
abbr .dt "$EDITOR ~/.darbs/TODO.md"
abbr .f "$EDITOR ~/.config/fish/config.fish"
abbr .fa "$EDITOR ~/.config/fish/abbrs.fish"
abbr .fb "$EDITOR ~/.config/fish/config.d/divramod.bindings.fish"
abbr .ff "$EDITOR ~/.config/fish/functions.fish"
abbr .g "$EDITOR ~/.gitconfig"
abbr .i "$EDITOR ~/.config/i3/config"
abbr .m "$EDITOR ~/.config/mutt/muttrc"
abbr .n "$EDITOR ~/.config/newsboat/config"
abbr .nb "$EDITOR ~/.config/ncmpcpp/bindings"
abbr .nc "$EDITOR ~/.config/ncmpcpp/config"
abbr .nu "$EDITOR ~/.config/newsboat/urls"
abbr .p "$EDITOR ~/.profile"
abbr .r "$EDITOR ~/.config/ranger/rc.conf"
abbr .s "$EDITOR ~/.darbs/scripts"
abbr .sh "$EDITOR ~/.shortcuts"
abbr .t "$EDITOR ~/.tmux.conf"
abbr .tb "$EDITOR ~/cod/te/bash/test.sh"
abbr .u "$EDITOR ~/.config/divramod/urls"
abbr .v "$EDITOR ~/.config/nvim/init.vim"
abbr .vau "$EDITOR ~/.config/nvim/init/topic/autocmd.vim"
abbr .vab "$EDITOR ~/.config/nvim/init/topic/abbreviations.vim"
abbr .vmi "$EDITOR ~/.config/nvim/init/topic/mappings_i.vim"
abbr .vmn "$EDITOR ~/.config/nvim/init/topic/mappings_n.vim"
abbr .vmv "$EDITOR ~/.config/nvim/init/topic/mappings_v.vim"
abbr .vp "$EDITOR ~/.config/nvim/init/topic/plugins.vim"
abbr .vs "$EDITOR ~/.config/nvim/plugged/vim-snippets/UltiSnips/sh/sh.snippets"
abbr .w "$EDITOR ~/art/wik/inb"
abbr .ws "$EDITOR ~/art/wik/inb/s7.md"
abbr .wt "$EDITOR ~/art/wik/inb/t460p.md"
abbr .ww "$EDITOR ~/art/wik/inb/workstation.md"
abbr .wx "$EDITOR ~/art/wik/inb/x121e.md"
abbr .xd "$EDITOR ~/.Xdefaults"
abbr .z "$EDITOR ~/.zshrc"
abbr .tl "$EDITOR ~/cod/wo/thingylabs/kubernetes-provisioning"
abbr .tlw "$EDITOR ~/art/wik/ref/thingylabs/_.md"
abbr .dw "$EDITOR ~/art/wik/ref/darbs/_.md"
