# vim: filetype=sh
abbr a "cd ~/art; and ls -a"
abbr cn "cd ~/.config; and ls -a"
abbr co "cd ~/cod; and ls -a"
abbr s "cd ~/.darbs/scripts; and ls -a"
abbr t "cd ~/.tmuxp; and ls -a"
abbr d "cd ~/.darbs; and ls -a"
abbr arc "cd ~/art/cam; and ls -a"
abbr arb "cd ~/art/bac; and ls -a"
abbr ard "cd ~/art/doc; and ls -a"
abbr are "cd ~/art/ema; and ls -a"
abbr arj "cd ~/art/jou; and ls -a"
abbr arn "cd ~/art/not; and ls -a"
abbr arp "cd ~/art/pro; and ls -a"
abbr arr "cd ~/art/ref; and ls -a"
abbr ars "cd ~/art/scr; and ls -a"
abbr ara "cd ~/art/sca; and ls -a"
abbr art "cd ~/art/tpl; and ls -a"
abbr arw "cd ~/art/wik; and ls -a"
abbr cgl "cd ~/cod/gl; and ls -a"
abbr cgh "cd ~/cod/gh; and ls -a"
abbr cwo "cd ~/cod/wo; and ls -a"
abbr cbb "cd ~/cod/bb; and ls -a"
abbr cte "cd ~/cod/te; and ls -a"
abbr des "cd ~/desk; and ls -a"
abbr doc "cd ~/doc; and ls -a"
abbr dow "cd ~/dow; and ls -a"
abbr mea "cd ~/med/aud; and ls -a"
abbr mee "cd ~/med/ebo; and ls -a"
abbr mei "cd ~/med/img; and ls -a"
abbr mem "cd ~/med/mus; and ls -a"
abbr mep "cd ~/med/pic; and ls -a"
abbr mes "cd ~/med/sof; and ls -a"
abbr mev "cd ~/med/vid; and ls -a"
abbr vbo "cd ~/vbo; and ls -a"
abbr cfvd "cd ~/.config/nvim; and ls -a"
abbr cfvb "cd ~/.config/nvim/plugged; and ls -a"
abbr cfvp "cd ~/.config/nvim/pack; and ls -a"
abbr cfvs "cd ~/.config/nvim/plugged/vim-snippets; and ls -a"
abbr cfp "cd ~/.tmuxp; and ls -a"
abbr boot "cd /boot; and ls -a"
abbr etc "cd /etc; and ls -a"
abbr home "cd /home; and ls -a"
abbr lost "cd /lost+found; and ls -a"
abbr mnt "cd /mnt; and ls -a"
abbr opt "cd /opt; and ls -a"
abbr proc "cd /proc; and ls -a"
abbr root "cd /root; and ls -a"
abbr run "cd /run; and ls -a"
abbr sys "cd /srv; and ls -a"
abbr tmp "cd /tmp; and ls -a"
abbr usr "cd /usr; and ls -a"
abbr var "cd /var; and ls -a"
abbr stg "cd ~/cod/gh/st; and ls -a"
abbr gtl "cd ~/cod/wo/thingylabs/kubernetes-provisioning; and ls -a"
abbr gtlc "cd ~/cod/wo/thingylabs/calponia; and ls -a"
abbr gse "cd ~/cod/gl/setup; and ls -a"
abbr .i "$EDITOR ~/.config/i3/config"
abbr .g "$EDITOR ~/.gitconfig"
abbr .d "$EDITOR ~/.darbs/README.md"
abbr .dt "$EDITOR ~/.darbs/docs/TODO.md"
abbr bmd "$EDITOR ~/.bmdirs"
abbr bmf "$EDITOR ~/.bmfiles"
abbr cfa "$EDITOR ~/.aliasrc"
abbr cfb "$EDITOR ~/.bashrc"
abbr cfd "$EDITOR ~/.Xdefaults"
abbr cff "$EDITOR ~/.config/fish/config.fish"
abbr cffa "$EDITOR ~/.config/fish/abbrs.fish"
abbr cffb "$EDITOR ~/.config/fish/config.d/divramod.bindings.fish"
abbr cfff "$EDITOR ~/.config/fish/functions.fish"
abbr cfg "$EDITOR ~/.gitconfig"
abbr cfi "$EDITOR ~/.config/i3/config"
abbr cfm "$EDITOR ~/.config/mutt/muttrc"
abbr cfmb "$EDITOR ~/.config/ncmpcpp/bindings"
abbr cfmc "$EDITOR ~/.config/ncmpcpp/config"
abbr cfn "$EDITOR ~/.config/newsboat/config"
abbr cfr "$EDITOR ~/.config/ranger/rc.conf"
abbr cft "$EDITOR ~/.tmux.conf"
abbr cfu "$EDITOR ~/.config/newsboat/urls"
abbr cfv "$EDITOR ~/.config/nvim/init.vim"
abbr cfvs "$EDITOR ~/.config/nvim/plugged/vim-snippets/UltiSnips/sh/sh.snippets"
abbr cfz "$EDITOR ~/.zshrc"
abbr csd "$EDITOR ~/.config/divramod/dirs.csv"
abbr csm "$EDITOR ~/.config/divramod/mounts.csv"
abbr csp "$EDITOR ~/cod/gl/setup/arch_manjaro_i3_progs.csv"
abbr csr "$EDITOR ~/.config/divramod/repos.csv"
abbr tes "$EDITOR ~/cod/te/bash/test.sh"
abbr wik "$EDITOR ~/art/wik/inb/sparkfile.md"
abbr wikt "$EDITOR ~/art/wik/inb/t460p.md"
abbr wiks "$EDITOR ~/art/wik/inb/s7.md"
abbr wikd "$EDITOR ~/art/wik/pla/days.md"
