#!/bin/bash
# call with: nohup st -e "fish" "-c" "wik_choose_ref mux" &
wik_path=~/art/wik
refs_path="${wik_path}"/ref
dir=$(find "${refs_path}" -maxdepth 1 ! -path . -type d -print0 | sort -z | while IFS= read -r -d $'\0' src_dir; do
  echo "${src_dir}"
done | fzf)
project_file="${dir}/_.md"
if [[ ! -f "${project_file}" ]]; then
  touch "${project_file}"
fi
shortcut=$(grep -ozP '(?s)```\n\K.*?(?=\n```)' "${project_file}")
if [[ -z "${1}" ]]; then
  eval "cd ${wik_path} && ${shortcut}"
else
  tmux new -c "${wik_path}" "${shortcut}"
fi
