#!/bin/sh

# Toggle floating dropdown terminal in i3, or start if non-existing.
# $1 is	the script run in the terminal.
# All other args are terminal settings.
# Terminal names are in dropdown_* to allow easily setting i3 settings.

[ -z "$1" ] && exit

# ------------------------------------------------------------------------------
# TODO document
close() {
  i3 "[instance=\"dropdown_tmuxdd_0\"] move scratchpad"
  i3 "[instance=\"dropdown_tmuxdd_1\"] move scratchpad"
  i3 "[instance=\"dropdown_tmuxdd_2\"] move scratchpad"
  i3 "[instance=\"dropdown_dropdownwiki\"] move scratchpad"
  i3 "[instance=\"dropdown_dropdowndarbs\"] move scratchpad"
}

if [[ "${1}" = "close" ]]; then
  close
else
  if xwininfo -tree -root | grep "(\"dropdown_$1\" ";
  then
    echo "Window detected."

    if [ "${1}" = "tmuxdd_0" ]; then
      i3 "[instance=\"dropdown_$1\"] scratchpad show; [instance=\"dropdown_$1\"] move position center"
    else
      i3 "[instance=\"dropdown_tmuxdd_0\"] move scratchpad"
    fi

    if [ "${1}" = "tmuxdd_1" ]; then
      i3 "[instance=\"dropdown_$1\"] scratchpad show; [instance=\"dropdown_$1\"] move position center"
    else
      i3 "[instance=\"dropdown_tmuxdd_1\"] move scratchpad"
    fi

    if [ "${1}" = "tmuxdd_2" ]; then
      i3 "[instance=\"dropdown_$1\"] scratchpad show; [instance=\"dropdown_$1\"] move position center"
    else
      i3 "[instance=\"dropdown_tmuxdd_2\"] move scratchpad"
    fi
    if [ "${1}" = "dropdownwiki" ]; then
      i3 "[instance=\"dropdown_$1\"] scratchpad show; [instance=\"dropdown_$1\"] move position center"
    else
      i3 "[instance=\"dropdown_dropdownwiki\"] move scratchpad"
    fi
    if [ "${1}" = "dropdowndarbs" ]; then
      i3 "[instance=\"dropdown_$1\"] scratchpad show; [instance=\"dropdown_$1\"] move position center"
    else
      i3 "[instance=\"dropdown_dropdowndarbs\"] move scratchpad"
    fi
  else
    echo "Window not detected... spawning."
    close
    i3 "exec --no-startup-id $TERMINAL -n dropdown_$1 $(echo "$@" | cut -d ' ' -f2-) -e $1"
  fi
fi
