# ansible-inventory
# Autogenerated from man page /usr/share/man/man1/ansible-inventory.1.gz
complete -c ansible-inventory -l ask-vault-pass --description 'ask for vault password.'
complete -c ansible-inventory -l export --description 'When doing an --list, represent in a way that is optimized for export,not as …'
complete -c ansible-inventory -l graph --description 'create inventory graph, if supplying pattern it must be a valid group name.'
complete -c ansible-inventory -l host --description 'Output specific host info, works as inventory script.'
complete -c ansible-inventory -l list --description 'Output all hosts info, works as inventory script.'
complete -c ansible-inventory -l playbook-dir --description 'Since this tool does not use playbooks, use this as a subsitute playbook dire…'
complete -c ansible-inventory -l vars --description 'Add vars to graph display, ignored unless used with --graph.'
complete -c ansible-inventory -l vault-id --description 'the vault identity to use.'
complete -c ansible-inventory -l vault-password-file --description 'vault password file.'
complete -c ansible-inventory -l version --description 'show program\'s version number and exit.'
complete -c ansible-inventory -s h -l help --description 'show this help message and exit.'
complete -c ansible-inventory -s i -l inventory -l inventory-file --description 'specify inventory host path or comma separated host list.'
complete -c ansible-inventory -s v -l verbose --description 'verbose mode (-vvv for more, -vvvv to enable connection debugging).'
complete -c ansible-inventory -s y -l yaml --description 'Use YAML format instead of default JSON, ignored for --graph ENVIRONMENT.'

