# ansible-doc
# Autogenerated from man page /usr/share/man/man1/ansible-doc.1.gz
complete -c ansible-doc -l version --description 'show program\'s version number and exit.'
complete -c ansible-doc -s F -l list_files --description 'Show plugin names and their source files without summaries (implies --list).'
complete -c ansible-doc -s M -l module-path --description 'prepend colon-separated path(s) to module library (default=[u\'/home/jenkins/.'
complete -c ansible-doc -s a -l all --description 'For internal testing only Show documentation for all plugins.'
complete -c ansible-doc -s h -l help --description 'show this help message and exit.'
complete -c ansible-doc -s j -l json --description 'For internal testing only Dump json metadata for all plugins.'
complete -c ansible-doc -s l -l list --description 'List available plugins.'
complete -c ansible-doc -s s -l snippet --description 'Show playbook snippet for specified plugin(s).'
complete -c ansible-doc -s t -l type --description 'Choose which plugin type (defaults to "module").'
complete -c ansible-doc -s v -l verbose --description 'verbose mode (-vvv for more, -vvvv to enable connection debugging) ENVIRONMEN…'

