# chwb
# Autogenerated from man page /usr/local/man/man1/chwb.1.gz
complete -c chwb -s c --description 'Set border color of wid to color.'
complete -c chwb -s s --description 'Set border width of wid to size.'

