# chwso
# Autogenerated from man page /usr/local/man/man1/chwso.1.gz
complete -c chwso -s i --description 'Invert wid Ns \\(cqs position in the window stack.'
complete -c chwso -s l --description 'Put wid at the bottom of the window stack.'
complete -c chwso -s r --description 'Put wid on top of the window stack.'

