# direnv-stdlib
# Autogenerated from man page /usr/share/man/man1/direnv-stdlib.1.gz
complete -c direnv-stdlib -l ad-hoc -l ad-hoc --description 'include --load which allows loading an environment from a file.'

