# dmenu
# Autogenerated from man page /usr/share/man/man1/dmenu.1.gz
complete -c dmenu -s h --description 'dmenu uses a menu line of at least \'height\' pixels tall, but no less than 8.'
complete -c dmenu -s x --description 'dmenu is placed at this offset measured from the left side of the monitor.'
complete -c dmenu -s y --description 'dmenu is placed at this offset measured from the top of the monitor.'

