# dqtool
# Autogenerated from man page /usr/share/man/man1/dqtool.1.gz
complete -c dqtool -l debug -s d --description '.'
complete -c dqtool -l help -s h --description '.'
complete -c dqtool -l template -s t --description '.'
complete -c dqtool -l verbose -s v --description '.'
complete -c dqtool -l version -s V --description '.'

