# git-secret-killperson
# Autogenerated from man page /usr/share/man/man1/git-secret-killperson.1.gz
complete -c git-secret-killperson -s h --description 'MANUAL Run man git-secret-killperson to see this note.'

