# git-secret-whoknows
# Autogenerated from man page /usr/share/man/man1/git-secret-whoknows.1.gz
complete -c git-secret-whoknows -s l --description '.'
complete -c git-secret-whoknows -s h --description 'MANUAL Run man git-secret-whoknows to see this note.'

