# git-secret-changes
# Autogenerated from man page /usr/share/man/man1/git-secret-changes.1.gz
complete -c git-secret-changes -s d --description '.'
complete -c git-secret-changes -s p --description '.'
complete -c git-secret-changes -s h --description 'MANUAL Run man git-secret-changes to see this note.'

