# git-secret-remove
# Autogenerated from man page /usr/share/man/man1/git-secret-remove.1.gz
complete -c git-secret-remove -s c --description '.'
complete -c git-secret-remove -s h --description 'MANUAL Run man git-secret-remove to see this note.'

