# git-secret-add
# Autogenerated from man page /usr/share/man/man1/git-secret-add.1.gz
complete -c git-secret-add -s i --description '.'
complete -c git-secret-add -s h --description 'MANUAL Run man git-secret-add to see this note.'

