# git-secret-reveal
# Autogenerated from man page /usr/share/man/man1/git-secret-reveal.1.gz
complete -c git-secret-reveal -s f --description '.'
complete -c git-secret-reveal -s F --description '.'
complete -c git-secret-reveal -s d --description '.'
complete -c git-secret-reveal -s p --description '.'
complete -c git-secret-reveal -s P --description '.'
complete -c git-secret-reveal -s h --description 'MANUAL Run man git-secret-reveal to see this note.'

