# git-secret-cat
# Autogenerated from man page /usr/share/man/man1/git-secret-cat.1.gz
complete -c git-secret-cat -s d --description '.'
complete -c git-secret-cat -s p --description '.'
complete -c git-secret-cat -s h --description 'MANUAL Run man git-secret-cat to see this note.'

