# git-secret-tell
# Autogenerated from man page /usr/share/man/man1/git-secret-tell.1.gz
complete -c git-secret-tell -s m --description '.'
complete -c git-secret-tell -s d --description '.'
complete -c git-secret-tell -s h --description 'MANUAL Run man git-secret-tell to see this note.'

