# git-secret-hide
# Autogenerated from man page /usr/share/man/man1/git-secret-hide.1.gz
complete -c git-secret-hide -s v --description '.'
complete -c git-secret-hide -s c --description '.'
complete -c git-secret-hide -s F --description '.'
complete -c git-secret-hide -s P --description '.'
complete -c git-secret-hide -s d --description '.'
complete -c git-secret-hide -s m --description '.'
complete -c git-secret-hide -s h --description 'MANUAL Run man git-secret-hide to see this note.'

