# git-secret-clean
# Autogenerated from man page /usr/share/man/man1/git-secret-clean.1.gz
complete -c git-secret-clean -s v --description '.'
complete -c git-secret-clean -s h --description 'MANUAL Run man git-secret-clean to see this note.'

