# ignw
# Autogenerated from man page /usr/local/man/man1/ignw.1.gz
complete -c ignw -s r --description 'Reset wid Ns \\(cqs override_redirect value to 0, unignoring the window.'
complete -c ignw -s s --description 'Set wid Ns \\(cqs override_redirect value to 1, ignoring the window.'

