# lsw
# Autogenerated from man page /usr/local/man/man1/lsw.1.gz
complete -c lsw -s a --description 'List all windows.'
complete -c lsw -s r --description 'Print the ID of the root window.'
complete -c lsw -s o --description 'List windows whose override_redirect attribute is set to 1.'
complete -c lsw -s u --description 'List unmapped (invisible) windows.'

