# mapw
# Autogenerated from man page /usr/local/man/man1/mapw.1.gz
complete -c mapw -s m --description 'Map (show) wid.'
complete -c mapw -s t --description 'Toggle wid Ns \\(cqs visibility.'
complete -c mapw -s u --description 'Unmap (hide) wid.'

