# mpc
# Autogenerated from man page /usr/share/man/man1/mpc.1.gz
complete -c mpc -s f -l format --description 'Configure the format used to display songs. sp The metadata delimiters are: .'
complete -c mpc -l wait --description 'Wait for operation to finish (e. g.  database update).'
complete -c mpc -l range --description 'Operate on a range (e. g.  when loading a playlist).'
complete -c mpc -s q -l quiet -l no-status --description 'Prevents the current song status from being printed on completion of some of …'
complete -c mpc -l verbose --description 'Verbose output.'
complete -c mpc -l host --description 'The MPD server to connect to.'
complete -c mpc -l port -s p --description 'The TCP port of the MPD server to connect to.'

