# newsboat
# Autogenerated from man page /usr/share/man/man1/newsboat.1.gz
complete -c newsboat -s h -l help --description 'Display help.'
complete -c newsboat -s r -l refresh-on-start --description 'Refresh feeds on start.'
complete -c newsboat -s e -l export-to-opml --description 'Export feeds as OPML to stdout.'
complete -c newsboat -s X -l vacuum --description 'Compact the cache by: 1) reclaiming the space that was left empty when data w…'
complete -c newsboat -s v -s V -l version --description 'Get version information about newsboat and the libraries it uses.'
complete -c newsboat -s i -l import-from-opml --description 'Import an OPML file.'
complete -c newsboat -s u -l url-file --description 'Use an alternative URL file.'
complete -c newsboat -s c -l cache-file --description 'Use an alternative cache file.'
complete -c newsboat -s C -l config-file --description 'Use an alternative configuration file.'
complete -c newsboat -s x -l execute --description 'Execute one or more commands to run newsboat unattended.'
complete -c newsboat -s l -l log-level --description 'Generate a logfile with a certain loglevel.  Valid loglevels are 1 to 6.'
complete -c newsboat -s d -l log-file --description 'Use this logfile as output when logging debug messages.'
complete -c newsboat -s E -l export-to-file --description 'Export a list of read articles (resp.  their GUIDs).'
complete -c newsboat -s I -l import-from-file --description 'Import a list of read articles and mark them as read if they are held in the …'

