# npm-token
# Autogenerated from man page /usr/share/man/man1/npm-token.1
complete -c npm-token -l ------+---------+------------+----------+----------------+ --description '| id     | token   | created    | read-only | CIDR whitelist | o 2.'

