# podboat
# Autogenerated from man page /usr/share/man/man1/podboat.1.gz
complete -c podboat -s h -l help --description 'Display help.'
complete -c podboat -s C -l config-file --description 'Use an alternative configuration file.'
complete -c podboat -s q -l queue-file --description 'Use an alternative queue file.'
complete -c podboat -s a -l autodownload --description 'Start automatic download of all queued files on startup.'
complete -c podboat -s l -l log-level --description 'Generate a logfile with a certain loglevel.  Valid loglevels are 1 to 6.'
complete -c podboat -s d -l log-file --description 'Use this logfile as output when logging debug messages.'

