# psc
# Autogenerated from man page /usr/share/man/man1/psc.1.gz
complete -c psc -s f --description 'Omit column width calculations.'
complete -c psc -s L --description 'Left justify strings. \\" ----------.'
complete -c psc -s k --description 'Keep all delimiters.'
complete -c psc -s r --description 'Output the data by row first then column.'
complete -c psc -s s --description 'Start the top left corner of the spreadsheet in   cell.'
complete -c psc -s R --description 'Increment by  n  on each new output row. \\" ----------.'
complete -c psc -s C --description 'Increment by  n  on each new output column. \\" ----------.'
complete -c psc -s n --description 'Output   n rows before advancing to the next column.'
complete -c psc -s d --description 'Use the single character  c as the delimiter between input fields.'
complete -c psc -s P --description 'Plain numbers only.'
complete -c psc -s S --description 'All numbers are strings. \\" ----------.'
complete -c psc -s v --description 'Print the version of psc.'

