# sc-im
# Autogenerated from man page /usr/share/man/man1/sc-im.1.gz
complete -c sc-im -l version --description 'Print the version number of Sc-im and exit.'
complete -c sc-im -l nocurses --description 'Run interactive but without ncurses interface.'
complete -c sc-im -l output --description 'Save the results in FILE.'
complete -c sc-im -l quit_afterload --description 'Quit after loading all the files.  Useful when sending scripts to SC-IM.'
complete -c sc-im -l autocalc --description 'Set variable \'autocalc\'.  Recalculations occur automatically.'
complete -c sc-im -l numeric --description 'Set variable \'numeric\'.'
complete -c sc-im -l half_page_scroll --description 'Set variable \'half_page_scroll\'.'
complete -c sc-im -l newline_action --description 'Set variable \'newline_action\' VAL to R j to move the cursor down after an ent…'
complete -c sc-im -l external_functions --description 'Set variable \'external_functions\'.  Enable external functions.'
complete -c sc-im -l xlsx_readformulas --description 'Set variable \'xlsx_readformulas\'.'

