# sc
# Autogenerated from man page /usr/share/man/man1/sc.1.gz
complete -c sc -s a --description 'Do not run the autorun macro, if one is specified in the file. \\" ----------.'
complete -c sc -s c --description 'Start the program with the recalculation being done in column order.'
complete -c sc -s e --description 'Start the program with round-to-even (banker\'s rounding) enabled.'
complete -c sc -s m --description 'Start the program with automatic recalculation disabled.'
complete -c sc -s n --description 'Start the program in quick numeric entry mode (see below). \\" ----------.'
complete -c sc -s o --description 'Start the program with automatic optimization of expressions enabled.'
complete -c sc -s q --description 'Quit after loading all files, but before becoming interactive.'
complete -c sc -s r --description 'Start the program with the recalculation being done in row order (default opt…'
complete -c sc -s v --description 'When piping data out using the  -P option (below), change all expressions to …'
complete -c sc -s x --description 'Cause the  Get and  Put commands (see below) to encrypt and decrypt data file…'
complete -c sc -s C --description 'Start the program with automatic newline action set to increment the column (…'
complete -c sc -s P --description 'PD Pipe a range to standard output.'
complete -c sc -s R --description 'Start the program with automatic newline action set to increment the row (see…'
complete -c sc -s W --description 'Pipe a range to standard output.'
complete -c sc -s 1 --description '(default) to disable this facility.'

