# simple-mtpfs
# Autogenerated from man page /usr/share/man/man1/simple-mtpfs.1.gz
complete -c simple-mtpfs -s o --description 'mount options.'
complete -c simple-mtpfs -s h -l help --description 'print help.'
complete -c simple-mtpfs -s V -l version --description 'print version . SS "SIMPLE-MTPFS options:".'
complete -c simple-mtpfs -s l -l list-devices --description 'list available MTP devices.  Supports <device> option.'
complete -c simple-mtpfs -l device --description 'select device no.  to mount.'
complete -c simple-mtpfs -s d --description 'enable debug output (implies -f).'
complete -c simple-mtpfs -s f --description 'foreground operation.'
complete -c simple-mtpfs -s s --description 'disable multi-threaded operation.'

