# stdiscosrv
# Autogenerated from man page /usr/share/man/man1/stdiscosrv.1.gz
complete -c stdiscosrv -o cert --description 'Certificate file (default â. /cert. pemâ).'
complete -c stdiscosrv -o db-dir --description 'Database directory, where data is stored (default â. /discovery. dbâ).'
complete -c stdiscosrv -o debug --description 'Enable debug output.'
complete -c stdiscosrv -o http --description 'Listen on HTTP (behind an HTTPS proxy).'
complete -c stdiscosrv -o key --description 'Key file (default â. /key. pemâ).'
complete -c stdiscosrv -o listen --description 'Listen address (default â:8443â).'
complete -c stdiscosrv -o metrics-listen --description 'Prometheus compatible metrics endpoint listen address (default disabled).'
complete -c stdiscosrv -o replicate --description 'Replication peers, \\%id@address <id@address>, comma separated.'
complete -c stdiscosrv -o replication-listen --description 'Listen address for incoming replication connections (default â:19200â).'

