# syslog-ng-debun
# Autogenerated from man page /usr/share/man/man1/syslog-ng-debun.1.gz
complete -c syslog-ng-debun -s r --description '.'
complete -c syslog-ng-debun -s h --description '.'
complete -c syslog-ng-debun -s l --description '.'
complete -c syslog-ng-debun -s d --description '.'
complete -c syslog-ng-debun -s R --description '.'
complete -c syslog-ng-debun -s W --description '.'
complete -c syslog-ng-debun -o Fedv -l enable-core --description 'options.'
complete -c syslog-ng-debun -s D --description '.'
complete -c syslog-ng-debun -s t --description '.'
complete -c syslog-ng-debun -s w --description '.'
complete -c syslog-ng-debun -s s --description '.'
complete -c syslog-ng-debun -s i --description '.'
complete -c syslog-ng-debun -s p --description '.'
complete -c syslog-ng-debun -s P --description '.'
complete -c syslog-ng-debun -o Fev --description 'syslog-ng-debun -r -p -d -w 5 -t 10 Collect pcap and debug mode output follow…'

