# unclutter
# Autogenerated from man page /usr/share/man/man1/unclutter.1.gz
complete -c unclutter -l timeout --description 'Specifies the number of seconds after which the cursor should be hidden if it…'
complete -c unclutter -l jitter --description 'Ignore cursor movements if the cursor hasn\\(cqt moved sufficiently far.'
complete -c unclutter -l exclude-root --description 'Don\\(cqt hide the mouse cursor if it is idling over the root window and not a…'
complete -c unclutter -l ignore-scrolling --description 'Ignore mouse scroll events (buttons 4 and 5) so that scrolling doesn\\(cqt unh…'
complete -c unclutter -l fork -s b --description 'Fork unclutter to the background.'
complete -c unclutter -l help -s h --description 'Display the usage and exit.'
complete -c unclutter -l version -s v --description 'Display the version and exit.'
complete -c unclutter -l display -s d --description '.'
complete -c unclutter -l idle --description '.'
complete -c unclutter -l keystroke --description '.'
complete -c unclutter -l grab --description '.'
complete -c unclutter -l noevents --description '.'
complete -c unclutter -l reset --description '.'
complete -c unclutter -l root --description '.'
complete -c unclutter -l onescreen --description '.'
complete -c unclutter -l not --description '.'

