# xcape
# Autogenerated from man page /usr/share/man/man1/xcape.1.gz
complete -c xcape -s d --description 'Debug mode.   Will run as a foreground process.'
complete -c xcape -s t --description 'Give a timeout in milliseconds.'
complete -c xcape -s e --description 'Use map-expression as the expression(s).'

