# xwallpaper
# Autogenerated from man page /usr/share/man/man1/xwallpaper.1.gz
complete -c xwallpaper -l center --description 'Centers the input file on the screen.'
complete -c xwallpaper -l daemon --description 'Keeps xwallpaper xwallpaper running in background, listening for RandR events.'
complete -c xwallpaper -l debug --description 'Displays debug messages on the standard error output while xwallpaper xwallpa…'
complete -c xwallpaper -l maximize --description 'Maximizes input file to fit screen without cropping.'
complete -c xwallpaper -l no-randr --description 'Ignores individual outputs and uses the whole screen instead.'
complete -c xwallpaper -l output --description 'Specifies the output on which a subsequently supplied file shall be set as wa…'
complete -c xwallpaper -l screen --description 'Specifies a screen by its screen number.'
complete -c xwallpaper -l stretch --description 'Stretches input file to fully cover the screen.'
complete -c xwallpaper -l tile --description 'Uses tiling mode.'
complete -c xwallpaper -l version --description 'Prints version and exits.'
complete -c xwallpaper -l zoom --description 'Zooms input file to fit screen with cropping.'

