#!/bin/bash

# helper
wik_path="${HOME}/art/wik"
cat_path="${wik_path}/aor"
src_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/$(basename "$0")"

# files
f1="${cat_path}/finance/expenses.md"

# tests
if [ -f "${f1}" ]; then
  touch "${f1}"
fi

# run
cd "${wik_path}" || exit
vim -p "${f1}" "${src_path}"
