#!/bin/bash
home="${HOME}"
wiki_dir="${home}/art/wik"
git_gitignore_autogenerate "${wiki_dir}"
cd "${wiki_dir}" || exit
res_git_add=$(git add -A)
notify-send "${res_git_add}"
if [ -z "${1}" ]; then
  res_git_commit=$(git commit -m "update")
  notify-send "${res_git_commit}"
else
  res_git_commit=$(git commit -m "${1}")
  notify-send "${res_git_commit}"
fi
res_git_pull=$(git pull)
notify-send "${res_git_pull}"
res_git_push=$(git push)
notify-send "${res_git_push}"
